repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.6  # Use the latest version
    hooks:
      - id: ruff
        args: [--fix]
        exclude: ^(bkse|models/guided_diffusion)/
      - id: ruff-format
        exclude: ^(bkse|models/guided_diffusion)/